// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxwpxkcvufuapaxgdxzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14d3B4a2N2dWZ1YXBheGdkeHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTIzOTEsImV4cCI6MjA2MTQ4ODM5MX0.FpZt4R0_1sCtpkpMJdZvO4_NdhAIVZVYwq0F8SRAMkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);